### ISSUE TITLE
.unique() requires the options

### ISSUE THREAD

**Issue by franciscop** [chancejs/chancejs#253]
When I try the example in Node.js:

```js
chance.unique(chance.state, 5);
```

It gives me the following error:

```bash
Uncaught TypeError: Cannot read property 'comparator' of undefined
      at Chance.unique (node_modules/chance/chance.js:306:33)
      at generateUsers (test/fixtures.js:43:31)
      [many more, but irrelevant]
```

Going to the source:

```js
Chance.prototype.unique = function(fn, num, options) {
    testRange(
        typeof fn !== "function",
        "Chance: The first argument must be a function."
    );

    var comparator = options.comparator || function(arr, val) { return arr.indexOf(val) !== -1; };

    // ...
```

It tries to access comparator of the object `options`, but options might not be defined. So, a proposed fix:

```js
Chance.prototype.unique = function(fn, num, options) {
    testRange(
        typeof fn !== "function",
        "Chance: The first argument must be a function."
    );

    // NEW
    options = options || {};

    var comparator = options.comparator || function(arr, val) { return arr.indexOf(val) !== -1; };

    // ...
```

And my temporary fix is just doing this:

```js
chance.unique(chance.state, 5, {});
```

Sorry I cannot make the PR right now, I'm super tight on a deadline to read and follow any process in place. Might try to do so in a couple of days (or if anyone else wants, sure, go ahead :smile: ).

**Comment by victorquinn** [comment]
Good catch @franciscop !
